### ISSUE TITLE
Utility: the ability to see what gets applied

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterPrefabs/LogStreamer#20] opened 2016-01-28 16:50 UTC
Would be useful to be able to configure the replicator (explicitly) to output all transaction/statements being applied to a certain instance. Either to the console, but preferably being able to route it to a diagnostic file.

Should of course be disabled by default.

**Comment by per-samuelsson** [comment] 2016-01-28 17:03
Lets put it in the log applicator layer even: https://github.com/Starcounter/Starcounter/issues/3320.

This issue will be about switching implementation based on some parameter / config.

**Comment by linkdata** [comment] 2016-01-29 07:13
Having such a log also store which application was doing the commits would be good for auditing.

Currently I use Fiddler to watch the WebSocket sessions. It has the advantage of seeing what was sent and received in real time, but unfortunately the sessions can't be saved by Fiddler, so they don't leave a permanent record.

**Comment by per-samuelsson** [comment] 2016-02-01 09:41
> Having such a log also store which application was doing the commits would be good for auditing.

Agree. Would be particularly useful for the case where you are trying to diagnose data flows that you don't want to happen between different replicas.

**Comment by linkdata** [comment] 2016-02-04 10:40
Closing this since it's now a duplicate of https://github.com/Starcounter/Starcounter/issues/3320.

**Closed by linkdata** 2016-02-04 10:40 UTC
Labels: enhancement
